/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author Dalvzam 
 * @author jaimegonher2
 */
public class Usuario extends javax.swing.JFrame {

    /**
     * Creates new form Usuario
     */
    public Usuario() {
        initComponents();
    }
    public static String fechaFormateada;
        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        PanelFechaTurno = new javax.swing.JPanel();
        Calendario = new com.toedter.calendar.JCalendar();
        PanelTurnos = new javax.swing.JPanel();
        textoTurnos = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Turno_1 = new javax.swing.JToggleButton();
        Turno_2 = new javax.swing.JToggleButton();
        Turno_3 = new javax.swing.JToggleButton();
        Turno_4 = new javax.swing.JToggleButton();
        Turno_5 = new javax.swing.JToggleButton();
        PanelLogo = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        PanelPistas = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jugador_Azul_1 = new javax.swing.JLabel();
        jugador_Azul_2 = new javax.swing.JLabel();
        jugador_Azul_3 = new javax.swing.JLabel();
        jugador_Azul_4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jugador_Morada_1 = new javax.swing.JLabel();
        jugador_Morada_2 = new javax.swing.JLabel();
        jugador_Morada_3 = new javax.swing.JLabel();
        jugador_Morada_4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jugador_Roja_1 = new javax.swing.JLabel();
        jugador_Roja_2 = new javax.swing.JLabel();
        jugador_Roja_3 = new javax.swing.JLabel();
        jugador_Roja_4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jugador_Verde_1 = new javax.swing.JLabel();
        jugador_Verde_2 = new javax.swing.JLabel();
        jugador_Verde_3 = new javax.swing.JLabel();
        jugador_Verde_4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 820));
        setResizable(false);

        bg.setMinimumSize(new java.awt.Dimension(1366, 820));
        bg.setPreferredSize(new java.awt.Dimension(1366, 820));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelFechaTurno.setBackground(new java.awt.Color(102, 102, 102));

        Calendario.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                CalendarioPropertyChange(evt);
            }
        });

        textoTurnos.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        textoTurnos.setText("Turnos");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        Turno_1.setText("16:00 - 17:00");
        Turno_1.setActionCommand("");
        Turno_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Turno_1ActionPerformed(evt);
            }
        });

        Turno_2.setText("17:00 - 18:00");
        Turno_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Turno_2ActionPerformed(evt);
            }
        });

        Turno_3.setText("18:00 - 19:00");
        Turno_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Turno_3ActionPerformed(evt);
            }
        });

        Turno_4.setText("19:00 - 20:00");
        Turno_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Turno_4ActionPerformed(evt);
            }
        });

        Turno_5.setText("20:00 - 21:00");
        Turno_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Turno_5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelTurnosLayout = new javax.swing.GroupLayout(PanelTurnos);
        PanelTurnos.setLayout(PanelTurnosLayout);
        PanelTurnosLayout.setHorizontalGroup(
            PanelTurnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTurnosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelTurnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(Turno_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Turno_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Turno_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Turno_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Turno_5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTurnosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(textoTurnos)
                .addGap(244, 244, 244))
        );
        PanelTurnosLayout.setVerticalGroup(
            PanelTurnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTurnosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textoTurnos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Turno_1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Turno_2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Turno_3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Turno_4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Turno_5)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        PanelLogo.setBackground(new java.awt.Color(102, 102, 102));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo_paddle.png"))); // NOI18N

        javax.swing.GroupLayout PanelLogoLayout = new javax.swing.GroupLayout(PanelLogo);
        PanelLogo.setLayout(PanelLogoLayout);
        PanelLogoLayout.setHorizontalGroup(
            PanelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLogoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelLogoLayout.setVerticalGroup(
            PanelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLogoLayout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jButton1.setBackground(new java.awt.Color(255, 102, 0));
        jButton1.setText("Cancelar Reserva");

        jButton2.setBackground(new java.awt.Color(255, 102, 0));
        jButton2.setText("Hacer Reserva\n");

        javax.swing.GroupLayout PanelFechaTurnoLayout = new javax.swing.GroupLayout(PanelFechaTurno);
        PanelFechaTurno.setLayout(PanelFechaTurnoLayout);
        PanelFechaTurnoLayout.setHorizontalGroup(
            PanelFechaTurnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Calendario, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
            .addComponent(PanelTurnos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelFechaTurnoLayout.createSequentialGroup()
                .addComponent(PanelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addGroup(PanelFechaTurnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PanelFechaTurnoLayout.setVerticalGroup(
            PanelFechaTurnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFechaTurnoLayout.createSequentialGroup()
                .addGroup(PanelFechaTurnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelFechaTurnoLayout.createSequentialGroup()
                        .addComponent(PanelLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelFechaTurnoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)))
                .addComponent(Calendario, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelTurnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bg.add(PanelFechaTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 780));

        PanelPistas.setBackground(new java.awt.Color(102, 102, 102));

        jPanel6.setBackground(new java.awt.Color(102, 102, 102));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pista_azul.png"))); // NOI18N

        jugador_Azul_1.setForeground(new java.awt.Color(255, 255, 255));
        jugador_Azul_1.setText("Sin Jugador");

        jugador_Azul_2.setForeground(new java.awt.Color(255, 255, 255));
        jugador_Azul_2.setText("Sin Jugador");

        jugador_Azul_3.setForeground(new java.awt.Color(255, 255, 255));
        jugador_Azul_3.setText("Sin Jugador");

        jugador_Azul_4.setForeground(new java.awt.Color(255, 255, 255));
        jugador_Azul_4.setText("Sin Jugador");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jugador_Azul_1, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                    .addComponent(jugador_Azul_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jugador_Azul_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jugador_Azul_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jugador_Azul_1)
                .addGap(18, 18, 18)
                .addComponent(jugador_Azul_2)
                .addGap(18, 18, 18)
                .addComponent(jugador_Azul_3)
                .addGap(18, 18, 18)
                .addComponent(jugador_Azul_4)
                .addGap(125, 125, 125))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pista_morada.png"))); // NOI18N

        jugador_Morada_1.setForeground(new java.awt.Color(255, 255, 255));
        jugador_Morada_1.setText("Sin Jugador");

        jugador_Morada_2.setForeground(new java.awt.Color(255, 255, 255));
        jugador_Morada_2.setText("Sin Jugador");

        jugador_Morada_3.setForeground(new java.awt.Color(255, 255, 255));
        jugador_Morada_3.setText("Sin Jugador");

        jugador_Morada_4.setForeground(new java.awt.Color(255, 255, 255));
        jugador_Morada_4.setText("Sin Jugador");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jugador_Morada_1, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                    .addComponent(jugador_Morada_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jugador_Morada_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jugador_Morada_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jugador_Morada_1)
                .addGap(18, 18, 18)
                .addComponent(jugador_Morada_2)
                .addGap(18, 18, 18)
                .addComponent(jugador_Morada_3)
                .addGap(18, 18, 18)
                .addComponent(jugador_Morada_4)
                .addGap(127, 127, 127))
        );

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pista_roja.png"))); // NOI18N

        jugador_Roja_1.setForeground(new java.awt.Color(255, 255, 255));
        jugador_Roja_1.setText("Sin Jugador");

        jugador_Roja_2.setForeground(new java.awt.Color(255, 255, 255));
        jugador_Roja_2.setText("Sin Jugador");

        jugador_Roja_3.setForeground(new java.awt.Color(255, 255, 255));
        jugador_Roja_3.setText("Sin Jugador");

        jugador_Roja_4.setForeground(new java.awt.Color(255, 255, 255));
        jugador_Roja_4.setText("Sin Jugador");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jugador_Roja_1, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                    .addComponent(jugador_Roja_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jugador_Roja_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jugador_Roja_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(13, 13, 13))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 26, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jugador_Roja_1)
                .addGap(18, 18, 18)
                .addComponent(jugador_Roja_2)
                .addGap(18, 18, 18)
                .addComponent(jugador_Roja_3)
                .addGap(18, 18, 18)
                .addComponent(jugador_Roja_4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(102, 102, 102));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pista_verde.png"))); // NOI18N

        jugador_Verde_1.setForeground(new java.awt.Color(255, 255, 255));
        jugador_Verde_1.setText("Sin Jugador");

        jugador_Verde_2.setForeground(new java.awt.Color(255, 255, 255));
        jugador_Verde_2.setText("Sin Jugador");

        jugador_Verde_3.setForeground(new java.awt.Color(255, 255, 255));
        jugador_Verde_3.setText("Sin Jugador");

        jugador_Verde_4.setForeground(new java.awt.Color(255, 255, 255));
        jugador_Verde_4.setText("Sin Jugador");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jugador_Verde_1, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                    .addComponent(jugador_Verde_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jugador_Verde_3, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                    .addComponent(jugador_Verde_4, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(0, 26, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(jugador_Verde_1)
                .addGap(18, 18, 18)
                .addComponent(jugador_Verde_2)
                .addGap(18, 18, 18)
                .addComponent(jugador_Verde_3)
                .addGap(18, 18, 18)
                .addComponent(jugador_Verde_4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelPistasLayout = new javax.swing.GroupLayout(PanelPistas);
        PanelPistas.setLayout(PanelPistasLayout);
        PanelPistasLayout.setHorizontalGroup(
            PanelPistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPistasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelPistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(PanelPistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(72, 72, 72))
        );
        PanelPistasLayout.setVerticalGroup(
            PanelPistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPistasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelPistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelPistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        bg.add(PanelPistas, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 830, 790));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 775, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
        private void CalendarioPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_CalendarioPropertyChange
            /*Cuando el valor del calendario cambie, cambio de formato la fecha y la almaceno */
            /* Todavia no se si usar la fecha formateada o ya procesada en partes */
            String pattern = "dd/MM/yyyy";
            DateFormat df = new SimpleDateFormat(pattern);
            Date fechaSinFormatear = Calendario.getDate();
            fechaFormateada = df.format(fechaSinFormatear);
    
        
        }//GEN-LAST:event_CalendarioPropertyChange
    
        private void Turno_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Turno_1ActionPerformed
            Turno_2.setSelected(false);
            Turno_3.setSelected(false);
            Turno_4.setSelected(false);
            Turno_5.setSelected(false);
            ActualizarPistas("1");
        }//GEN-LAST:event_Turno_1ActionPerformed
    
        private void Turno_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Turno_2ActionPerformed
            Turno_1.setSelected(false);
            Turno_3.setSelected(false);
            Turno_4.setSelected(false);
            Turno_5.setSelected(false);
            ActualizarPistas("2");
        }//GEN-LAST:event_Turno_2ActionPerformed
    
        private void Turno_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Turno_3ActionPerformed
            Turno_2.setSelected(false);
            Turno_1.setSelected(false);
            Turno_4.setSelected(false);
            Turno_5.setSelected(false);
            ActualizarPistas("3");
        }//GEN-LAST:event_Turno_3ActionPerformed
    
        private void Turno_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Turno_4ActionPerformed
            Turno_2.setSelected(false);
            Turno_3.setSelected(false);
            Turno_1.setSelected(false);
            Turno_5.setSelected(false);
            ActualizarPistas("4");
        }//GEN-LAST:event_Turno_4ActionPerformed
    
        private void Turno_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Turno_5ActionPerformed
            Turno_2.setSelected(false);
            Turno_3.setSelected(false);
            Turno_4.setSelected(false);
            Turno_1.setSelected(false);
            ActualizarPistas("5");
        }//GEN-LAST:event_Turno_5ActionPerformed
        
        public static void ActualizarPistas(String turnoSeleccionado){
            /* Cada vez que se seleccione un turno, las pistas se actualizarán y mostraran los jugadores */
            FileReader fr = null;
            BufferedReader br = null;
            File archivo = new File("src/Datos/reservas.csv");
            try{
                fr = new FileReader(archivo);
                br = new BufferedReader(fr);
                
                String linea;
                String fecha;
                String turno;
                String colorPista;
                String jugador1;
                String jugador2;
                String jugador3;
                String jugador4;
    
                while((linea = br.readLine()) != null){
                    String datosLeidos [] = linea.split(",");
                    if (datosLeidos.length == 7){
                        fecha = datosLeidos[0];
                        turno = datosLeidos[1];
                        colorPista = datosLeidos[2];
                        jugador1 = datosLeidos[3];
                        jugador2 = datosLeidos[4];
                        jugador3 = datosLeidos[5];
                        jugador4 = datosLeidos[6];
                        if (fecha.equals(fechaFormateada) && turno.equals(turnoSeleccionado)){
                            switch (colorPista) {
                                case "azul":
                                    jugador_Azul_1.setText(jugador1);
                                    jugador_Azul_2.setText(jugador2);
                                    jugador_Azul_3.setText(jugador3);
                                    jugador_Azul_4.setText(jugador4);
                                    break;
                                case "morada":
                                    jugador_Morada_1.setText(jugador1);
                                    jugador_Morada_2.setText(jugador2);
                                    jugador_Morada_3.setText(jugador3);
                                    jugador_Morada_4.setText(jugador4);
                                    break;
                                case "roja":
                                    jugador_Roja_1.setText(jugador1);
                                    jugador_Roja_2.setText(jugador2);
                                    jugador_Roja_3.setText(jugador3);
                                    jugador_Roja_4.setText(jugador4);
                                    break;
                                case "verde":
                                    jugador_Verde_1.setText(jugador1);
                                    jugador_Verde_2.setText(jugador2);
                                    jugador_Verde_3.setText(jugador3);
                                    jugador_Verde_4.setText(jugador4);
                                    break;
                                    
                                default:
                                    break;
                            }
                        }
                    }
                }   
        }catch(Exception e){
            e.printStackTrace();
        }finally{
            try {
                if (fr != null){
                    fr.close();
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JCalendar Calendario;
    private javax.swing.JPanel PanelFechaTurno;
    private javax.swing.JPanel PanelLogo;
    private javax.swing.JPanel PanelPistas;
    private javax.swing.JPanel PanelTurnos;
    private javax.swing.JToggleButton Turno_1;
    private javax.swing.JToggleButton Turno_2;
    private javax.swing.JToggleButton Turno_3;
    private javax.swing.JToggleButton Turno_4;
    private javax.swing.JToggleButton Turno_5;
    private javax.swing.JPanel bg;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JLabel jugador_Azul_1;
    public static javax.swing.JLabel jugador_Azul_2;
    public static javax.swing.JLabel jugador_Azul_3;
    public static javax.swing.JLabel jugador_Azul_4;
    public static javax.swing.JLabel jugador_Morada_1;
    public static javax.swing.JLabel jugador_Morada_2;
    public static javax.swing.JLabel jugador_Morada_3;
    public static javax.swing.JLabel jugador_Morada_4;
    public static javax.swing.JLabel jugador_Roja_1;
    public static javax.swing.JLabel jugador_Roja_2;
    public static javax.swing.JLabel jugador_Roja_3;
    public static javax.swing.JLabel jugador_Roja_4;
    public static javax.swing.JLabel jugador_Verde_1;
    public static javax.swing.JLabel jugador_Verde_2;
    public static javax.swing.JLabel jugador_Verde_3;
    public static javax.swing.JLabel jugador_Verde_4;
    private javax.swing.JLabel textoTurnos;
    // End of variables declaration//GEN-END:variables
}
